### ISSUE TITLE
Concern

### ISSUE THREAD

**Issue by RandomWolf** [mhkamal15/WizardWith4Guns-Mod#2]
Ive read the code, I see no way that I could work.

**Comment by RandomWolf** [comment]
*"it could work", excuse the mistake

**Comment by mhkamal15** [comment]
Hello there.
First of all, this copy is imported from my VSCode environment as a template. It was sent to the creator of the bounty I won to demonstrate my capabilities. The actual mod is a private Repl in my account, in compliance with the developer's wishes. They will release the full version when they can.

Secondly, could you enlighten me of your person please? I have told little people of this project (of the ones I have, they don't know where it's located) and your finding of it is engrossing to say the least.

Thank you for your observations however.

**Comment by RandomWolf** [comment]
I have found the bounty through a cursory Google search of "Wizard with a Gun 4 Player Mod".
From there, your profile was on the bounty page which also has your GitHub Info.
I was curious how you achieved 4 players, since I am also known to mod Wizard with A Gun.

I have also asked the project lead directly via Discord, and they did not remember asking anyone to not disclose modification code. Particularily as they have been open about modding the game so far.

Therefore I'm curious, how did you increase the max Players? Did you overwrite any checking code or changed an internal variable that has the max. amount of players?

**Comment by mhkamal15** [comment]
In the given code, the max player count is increased by changing the value of a variable for the maximum player count within the class responsible for co-op gameplay. In the template code, you can see that set to the maxplayercount variable.

Also, apologies. The creator has made me aware of your experience and I am very impressed. Maybe we could collab to work on this. In the meantime, he's clarified his intentions of making the mod completely public.

**Comment by RandomWolf** [comment]
Can I have some clarification? Do you mean the creator of the game, or the creator of the bounty on replit?
Alas, I have seen the same value in the code, but after checking further the provided variable is never used specifically to check the max. players, therefore changing it wouldnt work.

**Comment by mhkamal15** [comment]
I meant the creator of the bounty. 
Oh well. I thought it could would work.
Anyhow I've worked on another prototype script [here](https://github.com/mhkamal15/WizardWith4Guns-Mod/blob/main/wwg4patch.cs). 

Instead of just changing the value that version patches the EnableCoOp method instead of Enable2PlayerCoOp. This allows for bypassing the built-in 2-player limit. After calling the original EnableCoOp method, the code should set the internal maxPlayers field to 4. Then you can also optionally disable the Enable2PlayerCoOp method to further ensure 4-player functionality.

Let me know what you think.

**Comment by RandomWolf** [comment]
Thats an interesting approach!
It could work!

By the way, have you considered publishing your modification on a more available page, like [Thunderstore.io](https://thunderstore.io/c/wizard-with-a-gun/)? I have established a community there of people who are already modding the game, and it has some great responses from the community! So far we have three modders, me included, in the scene. I have even wrote a [More-than-4 player mod](https://thunderstore.io/c/wizard-with-a-gun/p/FoxMods/MorePlayers/) myself, about 1 day after the game released.

**Comment by mhkamal15** [comment]
> Thats an interesting approach! It could work!
> 
> By the way, have you considered publishing your modification on a more available page, like [Thunderstore.io](https://thunderstore.io/c/wizard-with-a-gun/)? I have established a community there of people who are already modding the game, and it has some great responses from the community! So far we have three modders, me included, in the scene. I have even wrote a [More-than-4 player mod](https://thunderstore.io/c/wizard-with-a-gun/p/FoxMods/MorePlayers/) myself, about 1 day after the game released.

Thanks! I figured it would be a more reliable way than changing the variables (especially given that as you mentioned, it wasn't called). Thanks also for the link to the community, I'll see if I can publish some mods there.
